import React, { useState } from 'react';
import { useLanguage } from '@/contexts/LanguageContext';
import { useAuth } from '@/contexts/AuthContext';
import { TeacherNavbar } from '@/components/TeacherNavbar';
import { StudentCard } from '@/components/StudentCard';
import { AddStudentDialog } from '@/components/AddStudentDialog';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Users, TrendingUp, AlertCircle, Sparkles, ArrowLeft } from 'lucide-react';
import { toast } from 'sonner';

interface Student {
  id: string;
  fullName: string;
  studentId: string;
  lastActive?: string;
  moodTrend?: 'up' | 'down' | 'stable';
  recentMood?: string;
}

interface StudentReport {
  studentId: string;
  student: Student;
  emotionalSummary: string;
  interests: string[];
  concerns: string[];
  weeklyMoods: { day: string; mood: string }[];
}

export const TeacherDashboard: React.FC = () => {
  const { t, language } = useLanguage();
  const { user } = useAuth();
  const [activeTab, setActiveTab] = useState('home');
  const [selectedStudentReport, setSelectedStudentReport] = useState<StudentReport | null>(null);
  
  // Mock data - will be connected to MongoDB later
  const [students, setStudents] = useState<Student[]>([
    {
      id: '1',
      fullName: '田中 花子',
      studentId: 'STU-2024-001',
      lastActive: '2時間前',
      moodTrend: 'up',
      recentMood: 'happy',
    },
    {
      id: '2',
      fullName: '佐藤 太郎',
      studentId: 'STU-2024-002',
      lastActive: '1日前',
      moodTrend: 'stable',
      recentMood: 'calm',
    },
    {
      id: '3',
      fullName: '鈴木 美咲',
      studentId: 'STU-2024-003',
      lastActive: '3時間前',
      moodTrend: 'down',
      recentMood: 'anxious',
    },
  ]);

  const handleAddStudent = async (studentId: string) => {
    // Placeholder - will connect to MongoDB
    const newStudent: Student = {
      id: Date.now().toString(),
      fullName: `New Student (${studentId})`,
      studentId,
      moodTrend: 'stable',
    };
    setStudents((prev) => [...prev, newStudent]);
  };

  const handleViewReport = (studentId: string) => {
    const student = students.find(s => s.id === studentId);
    if (student) {
      // Mock report data - will be generated by AI later
      setSelectedStudentReport({
        studentId,
        student,
        emotionalSummary: language === 'ja'
          ? 'この生徒は全体的にポジティブな感情を維持しています。最近、学業に関する不安が少し見られますが、友人関係は良好です。'
          : 'This student maintains generally positive emotions. There is some anxiety about academics recently, but friendships are going well.',
        interests: language === 'ja' 
          ? ['音楽', '読書', 'バスケットボール', 'ゲーム']
          : ['Music', 'Reading', 'Basketball', 'Gaming'],
        concerns: language === 'ja'
          ? ['数学のテストへの不安', '睡眠時間の不足']
          : ['Anxiety about math tests', 'Lack of sleep'],
        weeklyMoods: [
          { day: language === 'ja' ? '月' : 'Mon', mood: '😊' },
          { day: language === 'ja' ? '火' : 'Tue', mood: '😌' },
          { day: language === 'ja' ? '水' : 'Wed', mood: '😰' },
          { day: language === 'ja' ? '木' : 'Thu', mood: '😊' },
          { day: language === 'ja' ? '金' : 'Fri', mood: '🎉' },
        ],
      });
      setActiveTab('report-detail');
    }
  };

  const renderContent = () => {
    if (activeTab === 'report-detail' && selectedStudentReport) {
      return (
        <div className="space-y-6">
          <Button
            variant="ghost"
            onClick={() => {
              setSelectedStudentReport(null);
              setActiveTab('students');
            }}
            className="gap-2"
          >
            <ArrowLeft className="h-4 w-4" />
            {t('back')}
          </Button>

          <div className="flex items-center gap-4">
            <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center">
              <span className="text-2xl">👤</span>
            </div>
            <div>
              <h2 className="text-2xl font-bold">{selectedStudentReport.student.fullName}</h2>
              <p className="text-muted-foreground">ID: {selectedStudentReport.student.studentId}</p>
            </div>
          </div>

          {/* Weekly Mood */}
          <Card variant="elevated">
            <CardHeader>
              <CardTitle className="text-lg">{t('weeklyMood')}</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex justify-between">
                {selectedStudentReport.weeklyMoods.map((item, i) => (
                  <div key={i} className="text-center">
                    <div className="text-2xl mb-1">{item.mood}</div>
                    <div className="text-xs text-muted-foreground">{item.day}</div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* AI Summary */}
          <Card variant="lavender">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <Sparkles className="h-5 w-5" />
                {t('moodOverview')}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-foreground">{selectedStudentReport.emotionalSummary}</p>
            </CardContent>
          </Card>

          {/* Interests */}
          <Card variant="elevated">
            <CardHeader>
              <CardTitle className="text-lg">{t('interests')}</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-2">
                {selectedStudentReport.interests.map((interest, i) => (
                  <span
                    key={i}
                    className="px-3 py-1 bg-sky-light text-sky-foreground rounded-full text-sm"
                  >
                    {interest}
                  </span>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Concerns */}
          <Card variant="elevated">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <AlertCircle className="h-5 w-5 text-peach" />
                {t('concerns')}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                {selectedStudentReport.concerns.map((concern, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-peach">•</span>
                    <span>{concern}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </div>
      );
    }

    switch (activeTab) {
      case 'students':
        return (
          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <h2 className="text-xl font-semibold">{t('myStudents')}</h2>
              <AddStudentDialog onAddStudent={handleAddStudent} />
            </div>
            
            {students.length === 0 ? (
              <Card variant="outline" className="text-center py-12">
                <CardContent>
                  <Users className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
                  <p className="text-muted-foreground">{t('noStudentsYet')}</p>
                </CardContent>
              </Card>
            ) : (
              <div className="space-y-3">
                {students.map((student) => (
                  <StudentCard
                    key={student.id}
                    student={student}
                    onViewReport={handleViewReport}
                  />
                ))}
              </div>
            )}
          </div>
        );
      case 'reports':
        return (
          <div className="space-y-6">
            <h2 className="text-xl font-semibold">{t('studentReports')}</h2>
            <Card variant="elevated">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingUp className="h-5 w-5 text-mint" />
                  {t('emotionalTrends')}
                </CardTitle>
                <CardDescription>
                  {language === 'ja' 
                    ? 'AI分析はZ.AI APIキーを設定した後に有効になります'
                    : 'AI analysis will be enabled after configuring your Z.AI API key'}
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="h-48 flex items-center justify-center border-2 border-dashed border-border rounded-xl">
                  <p className="text-muted-foreground text-sm">
                    {language === 'ja' ? 'グラフがここに表示されます' : 'Chart will appear here'}
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>
        );
      case 'settings':
        return (
          <div className="space-y-6">
            <h2 className="text-xl font-semibold">{t('settings')}</h2>
            <Card variant="elevated">
              <CardHeader>
                <CardTitle>{t('profile')}</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-center gap-4">
                  <div className="w-20 h-20 rounded-full bg-lavender/20 flex items-center justify-center">
                    <span className="text-3xl">👨‍🏫</span>
                  </div>
                  <div>
                    <h3 className="text-xl font-semibold">{user?.fullName}</h3>
                    <p className="text-muted-foreground">{user?.email}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        );
      default:
        return (
          <div className="space-y-6">
            {/* Welcome */}
            <div className="text-center py-6">
              <h2 className="text-2xl font-bold text-foreground mb-2">
                {language === 'ja' 
                  ? `おかえりなさい、${user?.fullName?.split(' ')[0] || '先生'}！`
                  : `Welcome back, ${user?.fullName?.split(' ')[0] || 'Teacher'}!`}
              </h2>
              <p className="text-muted-foreground">
                {language === 'ja' 
                  ? '生徒たちの様子を確認しましょう'
                  : "Let's check on your students"}
              </p>
            </div>

            {/* Quick Stats */}
            <div className="grid grid-cols-2 gap-4">
              <Card variant="sakura">
                <CardContent className="p-4 text-center">
                  <div className="text-3xl font-bold text-foreground">{students.length}</div>
                  <div className="text-sm text-muted-foreground">{t('students')}</div>
                </CardContent>
              </Card>
              <Card variant="sky">
                <CardContent className="p-4 text-center">
                  <div className="text-3xl font-bold text-foreground">
                    {students.filter(s => s.lastActive?.includes('時間') || s.lastActive?.includes('hour')).length}
                  </div>
                  <div className="text-sm text-muted-foreground">{t('recentActivity')}</div>
                </CardContent>
              </Card>
            </div>

            {/* Recent Students */}
            <div>
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-semibold">{t('recentActivity')}</h3>
                <Button variant="ghost" size="sm" onClick={() => setActiveTab('students')}>
                  {language === 'ja' ? 'すべて見る' : 'View All'}
                </Button>
              </div>
              <div className="space-y-3">
                {students.slice(0, 3).map((student) => (
                  <StudentCard
                    key={student.id}
                    student={student}
                    onViewReport={handleViewReport}
                  />
                ))}
              </div>
            </div>
          </div>
        );
    }
  };

  return (
    <div className="min-h-screen bg-background">
      <TeacherNavbar activeTab={activeTab} onTabChange={setActiveTab} />
      
      <main className="pt-20 md:pt-24 pb-24 md:pb-8 px-4 md:px-6">
        <div className="max-w-3xl mx-auto">
          {renderContent()}
        </div>
      </main>

      {/* Decorative Background */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden -z-10">
        <div className="absolute top-0 left-0 w-full h-64 gradient-hero opacity-30" />
      </div>
    </div>
  );
};

export default TeacherDashboard;
